### ISSUE TITLE
use trex version v2.54 or later for 1G hugepages

### ISSUE THREAD

**Issue by venkataanil** [atheurer/trafficgen#128]
pbench-trafficgen is failing as trex version (v2.53) which it installed supports only 2048kB. 
Error log is at https://gist.github.com/venkataanil/e1eb537e7590301bf637abbe52e82513 

May be we need to install v2.54 [1] which supports 1G hugepages [2]

[1] https://github.com/atheurer/trafficgen/blob/master/install-trex.sh#L5
[2] https://github.com/cisco-system-traffic-generator/trex-core/commit/622a8a1321f5bfa43763a770af1ab729e08a8a10

**Comment by pradiptapks** [comment]
Ensure the Trex host primarily configured with hugepage.

For debugging, the following manual config can help to ensure trex-server (v2.53) is supported or not.

`
# cat /etc/trex_cfg.yaml
  limit_memory: 18432  ### Huge page configuration.
`

For insight debug log, the following command can help:
./t-rex-64 -i -c $number_of_cores --cfg /etc/trex_cfg.yaml -v 7

The above configuration work with following Trex version.

http://trex-tgn.cisco.com/trex/release/v2.61.tar.gz
https://trex-tgn.cisco.com/trex/release/v2.65.tar.gz

**Comment by pradiptapks** [comment]
For huge page, I think the following configuration needs to update with "limit_memory" parameter.
```
# cat /var/lib/pbench-agent/tmp/trex_cfg.yaml
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['5e:00.2', '5e:00.3']
  port_info:
      - ip: 1.1.1.1
        default_gw: 2.2.2.2
      - ip: 2.2.2.2
        default_gw: 1.1.1.1

  platform:
      master_thread_id: 9
      latency_thread_id: 8
      dual_if:
        - socket: 0
          threads: [2,3,4,5,6,7]

```
Some debug information for further tunning:
```
Using configuration file /var/lib/pbench-agent/tmp/trex_cfg.yaml 
 port limit     :  not configured 
 port_bandwidth_gb    :  10 
 if_mask        : None 
 is low-end : 0 
 stack type :  
 thread_per_dual_if      : 1 
 if        :  5e:00.2, 5e:00.3,
 enable_zmq_pub :  1 
 zmq_pub_port   :  4500 
 m_zmq_rpc_port    :  4501 
 src     : 00:00:00:00:00:00
 dest    : 00:00:00:00:00:00
 src     : 00:00:00:00:00:00
 dest    : 00:00:00:00:00:00
 memory per 2x10G ports  
 MBUF_64                                   : 16380 
 MBUF_128                                  : 8190 
 MBUF_256                                  : 8190 
 MBUF_512                                  : 8190 
 MBUF_1024                                 : 8190 
 MBUF_2048                                 : 4095 
 MBUF_4096                                 : 128 
 MBUF_9K                                   : 512 
 TRAFFIC_MBUF_64                           : 65520 
 TRAFFIC_MBUF_128                          : 32760 
 TRAFFIC_MBUF_256                          : 8190 
 TRAFFIC_MBUF_512                          : 8190 
 TRAFFIC_MBUF_1024                         : 8190 
 TRAFFIC_MBUF_2048                         : 32760 
 TRAFFIC_MBUF_4096                         : 128 
 TRAFFIC_MBUF_9K                           : 512 
 MBUF_DP_FLOWS                             : 524288 
 MBUF_GLOBAL_FLOWS                         : 5120 
 master   thread  : 9  
 rx  thread  : 8  
 dual_if : 0 
    socket  : 0  
   [   2   3   4   5   6   7     ]  

<..trim..>

DPDK args 
 xx  -l  9,8,2,3,4,5,6,7  -n  4  --log-level  5  --master-lcore  9  -w  0000:5e:00.2  -w  0000:5e:00.3  --legacy-mem  
 EAL: Could not find space for memseg. Please increase CONFIG_RTE_MAX_MEMSEG_PER_TYPE and/or CONFIG_RTE_MAX_MEM_PER_TYPE in configuration.
EAL: Couldn't remap hugepage files into memseg lists
EAL: FATAL: Cannot init memory
EAL: Cannot init memory
 You might need to run ./trex-cfg  once  
EAL: Error - exiting with code: 1
  Cause: Invalid EAL arguments
Killing Scapy server
```
